### ISSUE TITLE
Combine and parameterize seed data files

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1089]
Dev seeds should have minimal data- basically one of each type
QA and Staging should have lots and lots (for realistic test data)

`seeds/dev.rb`-> `Seeder.new(1, 1, 3).run()` (example)
`seeds/qa.rb`-> `Seeder.new(100, 100, 3).run()` (example)
`seeds/staging.rb`-> `Seeder.new(100, 100, 3, random: false).run()` (example)

- [ ] combine dev, qa, staging seed files (remove code duplication)
- [ ] parametrize how many of each type are generated
- [ ] introduce TPM as well as CINA case numbers (the rest of the string stays the same)
- [ ] make sure that `rake db:seed:replant` works (not missing any delete statements up top)
- [ ] testing - try for speed. Keep or improve functionality in `seeds_spec.rb`
- [ ] bonus: provide an option to un-random faker https://github.com/faker-ruby/faker#deterministic-random
- [ ] bonus: introduce a seed value (like rspec) !!

**Comment by keithrbennett** [comment]
I think I'd like to separate this out into two PR's: 1 to combine and parameterize existing seed functionality, and 1 to add to the existing functionality. The two are cleanly separable and it would be helpful for the 2nd to be dealing with a single parameterized seeds file as the baseline rather than the multiple files. Is this ok? Should they maybe even be 2 separate issues?

**Comment by compwron** [comment]
Sounds good, go for it.

**Comment by keithrbennett** [comment]
@compwron I am reopening this issue, as the recent PR was just one of multiple PR's that will be needed for this issue.

**Comment by keithrbennett** [comment]
@compwron Currently, in staging, transition_aged_youth is always set to false, but in qa it alternates between true and false. Should we change staging to also include instances of both true and false for transition_aged_youth?
