### ISSUE TITLE
In Case Contact Report, Contact Types filter do not when one or more options are selected

### ISSUE THREAD

**Issue by erik-trantt** [rubyforgood/casa#1138]
Sample params of a report request:

{
"start_date"=>"2020-05-19", 
"end_date"=>"2020-10-20", 
"supervisor_ids"=>["", "2"], 
"creator_ids"=>["", "1"], 
"contact_type_ids"=>["", "1", "2"], 
"contact_type_group_ids"=>["", "1", "2", "3", "4", "5", "6"], 
"want_driving_reimbursement"=>"true", 
"contact_made"=>"false", 
"has_transitioned"=>"", 
"commit"=>"Download Report"
}

Identified a bunch of other bugs relating to scopes of CaseContact used in CaseContactReport filters at:
- /case_contact_reports

3. Contact Types filters **do not** work properly. If none is selected, it will accept all `contact_types`, which is expected. If one or more options are selected, the query is comparing `contact_types.name` against `contact_type.ids`.

```rb
# app/models/case_contact.rb
  scope :contact_type, ->(contact_type = nil) {
    if contact_type.present?
      joins(:contact_types)
        .where("contact_types.name in (?)", contact_type)
    end
  }
```

There are 2 ways to fix this:

1. Change to use `contact_types`.`id` for filtering. It is similar to the bug of this issue:
```rb
  scope :contact_type, ->(contact_type_ids = nil) {
    if contact_type.present?
      joins(:contact_types)
        .where(contact_types.id: contact_type_ids)
    end
  }
```

2. Change the generate values of options element of Contact Type to `name` from `id`:

![image](https://user-images.githubusercontent.com/44339322/96472459-35a23680-127c-11eb-93d1-1a01ed92ad3d.png)
![image](https://user-images.githubusercontent.com/44339322/96472492-43f05280-127c-11eb-948d-5cdf9a613261.png)

_Originally posted by @erik-trantt in https://github.com/rubyforgood/casa/issues/1117#issuecomment-712247123_

**Comment by cassianoblonski** [comment]
got this

**Comment by cassianoblonski** [comment]
@erik-trantt if Youth and Supervisor are selected to filter the response, it needs to bring CaseContact that has both options or at least one?

example
`CaseContact Number 1` has: Youth and Supervisor
`CaseContact Number 2` has: Youth
`CaseContact Number 3` has: Parent


solution 1: if you select both options(Youth, Supervisor) on the filter it will return only `CaseContact Number 1` because the contact is the only one that owns the 2 types

solution 2: will return CaseContacs 1 and 2 because it matches if the CaseContact has Youth or Supervisor, CaseContact3 doesn't have any of then so it will not be returned

**Comment by erik-trantt** [comment]
> ```ruby
>         .where("contact_types.name in (?)", contact_type)
> ```

I'm not totally familiar with the original scope of this report. But looking at the current implementation, I think solution 2 would be more close to my understanding of how the report works.

Maybe we should get some words of wisdom from @Zrrrpy @compwron 🤓

**Comment by cassianoblonski** [comment]
Okay, that's the solution that I worked on, opening the PR so your guys can see and review
