### ISSUE TITLE
Revisiting Standardrb Rules

### ISSUE THREAD

**Issue by keithrbennett** [rubyforgood/casa#1164]
I just ran standardrb --fix on master and viewed the differences. I believe that some of the rules it enforces are examples of poorer, not better code. I'd like to see if we can get consensus on any of this, and if so, I volunteer to implement the changes. Here are the issues I found:

### Horizontal Alignment of Values and Blocks

![image](https://user-images.githubusercontent.com/28410/96820695-7de46480-13f4-11eb-9131-b76684a8c038.png)
![image](https://user-images.githubusercontent.com/28410/96820719-89d02680-13f4-11eb-9b0e-deb972c65cda.png)

This is one of the most egregious ones because it violates basic user interface design principles. Horizontally aligning the values allows the reader to spot the values with a minimum of eye movement and effort. Would any of us ever implement text fields in a web form in this way, where labels are horizontally aligned, but the input fields are horizontally scattered? Why aren't we developers worthy of the same consideration as our users?

### And vs. &&

![image](https://user-images.githubusercontent.com/28410/96820782-aff5c680-13f4-11eb-9a5f-8357bd312af1.png)

The prevailing wisdom, as I understand it, is that `&&/||` should be used for logical operations but that `and/or` should be used for flow control (see Avdi Grimm's article at https://avdi.codes/using-and-and-or-in-ruby/). So `and/or` should be allowed. Also, the two pairs differ in precedence rules; I wonder if this could result in runtime errors in some cases as well.

### Parenthesizing Ternary Conditions

![image](https://user-images.githubusercontent.com/28410/96820821-bf750f80-13f4-11eb-84d9-8a6348ad344a.png)

It is often helpful to the reader to wrap a ternary expression's condition in  in parentheses, to explicitly show its beginning and end. This is especially true when the condition is more complex than the one in this example.

### Method Parameter Indentation

![image](https://user-images.githubusercontent.com/28410/96820859-d4ea3980-13f4-11eb-9a32-4d0109f2c934.png)

The example in this image is not so bad, but I've seen cases where horizontal space is limited, and this formatting style pushes parameters way to the right, sometimes out of view.

### Expression Continuation Indentation

![image](https://user-images.githubusercontent.com/28410/96821521-09aac080-13f6-11eb-8fcd-c18e06317229.png)

A somewhat related issue is that this single-indentation-level rule makes it impossible to distinguish (by spacing at least) _expression continuations_ from _changes in nesting levels_. A convention that has been used by many, for many years, is _continuation indentation_, which is typically _two_ indentation levels (as shown on the left). My editor, RubyMine, has a separate setting for continuation indents, and possibly many others do as well.

It helps because when scanning the code one can easily spot the horizontal distance between left margins of the first and subsequent lines, and immediately know, before even looking at any text, whether it is a change in nesting level or an expression continuation. This communicates information to the reader that would otherwise not be available before mentally parsing the code itself.

This image is not a great example but was the only one I noticed; a better one would have line continuation and nesting level changes in the same block of code.

### Use of ".()" as an Abbreviation for ".call("

![image](https://user-images.githubusercontent.com/28410/96820909-efbcae00-13f4-11eb-8967-733ea8c7c66b.png)

Callables are objects that respond to a `call` method, and can include Proc's (lambdas and non-lambda procs), and other classes. Procs/lambdas are first class objects in Ruby, and the addition to the language of the stabby lambda and `.()` notations were nods to the importance of functional programming in Ruby. Prohibiting the use of this abbreviation undoes a Ruby feature that was put there to help us. I realize that it is unfamiliar at first, but the mental translation of `.()` to `.call()` is a small jump. Using `.call` seems innocuous when it is only occasional, but as it is used more, the verbosity becomes distracting and annoying.

### Replacing do/end with {}

![image](https://user-images.githubusercontent.com/28410/96820935-f8ad7f80-13f4-11eb-9699-f94ac0c3490e.png)

This was the most surprising one to me. I would have expected the reverse to be enforced, since using `do/end` for multiline blocks has been a convention for many years now.

### Prohibiting Spaces for {}

![image](https://user-images.githubusercontent.com/28410/96822107-4a570980-13f7-11eb-9e9f-677483774b13.png)

This one was surprising to me too. I suppose one could justify it by saying we do the same thing with parentheses in method calls, but it's a very uncommon pattern, at least in my experience.

### Enforcing Double Quotes

![image](https://user-images.githubusercontent.com/28410/96822206-87230080-13f7-11eb-85dd-4faa13876cb1.png)

There have been many times when I have had to input many quoted strings, and I've long appreciated being able to avoid the Shift key when doing so. It would be nice to continue to have the option to use single quotes.

**Comment by littleforest** [comment]
Here are my two cents:

Re **Horizontal Alignment of Values and Blocks** - I rarely encounter Ruby code that horizontally aligns the values. I came to Ruby from Perl, and in Perl we always horizontally aligned, but I found that as I worked with other Ruby developers that they rarely horizontally aligned. I prefer to not horizontally align the values as I feel like most Ruby developers do not.

Re **And vs. &&** - I agree about the flow control, but for most cases I think it's easier to use &&/|| and avoid unintended bugs, and also is easier for newer developers. HOWEVER, I really DO NOT like `redirect_to(case_court_reports_path) && return` (does that even work???). Are we allowed to make exceptions when reviewing the linting? It is a common Rails expression to write `redirect_to case_court_reports_path and return` and I would hate that those get rewritten.

Re **Parenthesizing Ternary Conditions** - I like fewer parentheses for readability if they are unnecessary. Is this something that we have to require? To me it doesn't seem like we need a rule for this. People can just use what's easiest to read.

Re **Method Parameter Indentation** - I agree re things getting pushed too far to the right. I actually like the format like this:
```
update(
  foo: "bar",
  baz: "zoo",
  ...
)
```
but I don't know if that's an option or how others feel about it. I like it because it doesn't have the problem of items too far to the right, and everything is left-justified.

Re **Expression Continuation Indentation** - no strong feelings except that I think the distinction may be lost on people.

Re **Use of ".()" as an Abbreviation for ".call()"** - no strong feelings except that I think most people are more familiar with `call` as the notation and it is easier to read and follow (especially for newer developers). Again, I see `call` a lot, but rarely `.()` in the Rails projects I have worked on. But maybe other people have the reverse experience!

Re **Replacing do/end with {}** -- this one seems really weird to me too! I do not like this rule, or would at least like the option to use either. This is the kind of thing that I don't think we really need a rule for, that it should just be what is best for readability, but feels really strange to not use `do/end` for multiline expressions.

Re **Prohibiting Spaces for {}** - I prefer the spaces for readability as well.

Re **Enforcing Double Quotes** - I think consistency is important, so I prefer one or the other. I like double quotes due to being able to interpolate. With all single quotes, you end up having to switch to double for interpolation which then I think looks weird. But lots of people prefer single quotes, so no strong feelings, just would like consistency.

**Comment by jmkoni** [comment]
The point of using standard (which we do) is so that we do not spend time on these discussions. I do not think we should change any of these because almost all of these are preferences. Individuals will all have different preferences and we use standard so we can avoid this type of conflict.

**Comment by littleforest** [comment]
Thanks @jmkoni ! Sorry, I wasn't familiar enough with the standardrb gem to understand that it discouraged overrides. I think we can just close this then for now.

**Comment by keithrbennett** [comment]
@jmkoni Although there is a component of personal preference, there is also a component of objective merits. The concerns I raised are not equal in importance, but the way I see it, to dismiss _all_ these concerns is to knowingly condemn the code base to reduced clarity for the lifetime of the project.  As examples:

* the prohibition on horizontal alignment violates user interface design rules, making the terms on the right (e.g. hash values) virtually impossible to view separately from the terms on the left (e.g. hash keys).
* the 'no spaces to pad curly braces' rule compels developers to learn a new habit that is not even widely used
* the 'no parentheses around ternary expression conditions ties the hands of a developer who wants to make the expression easier to read (to be clear, I am advocating _no_ rule on this, not mandatory parentheses).
* the method parameter position requirement risks truncating the view of that code; removing that requirement would let the developer remedy that (or, alternatively, mandating 1 or 2 indentation levels would remedy that as well).

@littleforest I don't think the fact that the standardrb gem discourages deviation should be a controlling factor. We developers should be the masters of the tools, and not vice versa.

I understand the reluctance to invest time in coming to agreement, but I don't think it needs to take that long.

**Comment by jmkoni** [comment]
Again, those are still your opinions... these rules have been decided on by others (not me) so that your average ruby code base does not have to think about these. You can look up these rules in rubocop for the original reason behind them and often, if there is not consensus, there will be an open issue with a debate on why that rule was chose. I am closing this, again, because this is the entire reason we are using standard. So we do not spend time on this debate. Feel free to open up an issue within standard if you strongly disagree with these rules (https://github.com/testdouble/standard/issues). This is not something we are going to spend time debating in CASA.
