### ISSUE TITLE
RuboCop: 4953 offenses

### ISSUE THREAD

**Issue by jhsu802701** [rubyforgood/casa#1296]
This app currently has 4953 RuboCop offenses.  Only 4560 are auto-correctable.  (This leaves 393 that are not auto-correctable.)

Do we intend to make this app RuboCop-compliant?  If not, rubocop should be removed from the Gemfile.

**Comment by jmkoni** [comment]
Hi. Rubocop is not actually in our Gemfile, standard is. It is in the Gemfile.lock because it's a dependency of standard. If you run `standardrb --fix`, you should have a clean build. So to answer your question: no, we do not intend to make this app Rubocop-compliant because it is standard compliant 😃
