### ISSUE TITLE
Use our Dockerfile in CI build as a way of making sure it always works

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1365]
Use our Dockerfile in CI build as a way of making sure it always works

@littleforest this is just an idea I had. Does this seem like a good idea to you?

**Comment by littleforest** [comment]
@compwron do you mean as a separate action (we would also run the non-Docker build)?

**Comment by compwron** [comment]
I see no reason to run both, might as just run the whole build on docker

**Comment by littleforest** [comment]
I just ran into a situation with the Rack Attack specs where I broke it for non-Docker setups (fortunately I was testing on both). Since I'm assuming most people are NOT using the Docker setup, I think it's important that we still run the regular specs. Is there a way we can run both, or does our whole setup depend on using one or the other?

**Comment by jhsu802701** [comment]
I've tried to test Docker setups on other projects in the past, and I found that Docker didn't work the same in CI as it does on my local machine.

**Comment by compwron** [comment]
@littleforest We can definitely run both (github actions is very cool), I just wasn't aware of the value of doing so. Makes sense. 

@jhsu802701 What do you mean? Do you remember any details?

**Comment by jhsu802701** [comment]
I recall that there were permission issues.
