### ISSUE TITLE
Fix rake task that sends out court report reminders

### ISSUE THREAD

**Issue by littleforest** [rubyforgood/casa#1386]
**What is the problem, and what should happen instead?**
`court_report_submitted` has been replaced by `court_report_submitted_at` and `court_report_status`.

- [x] Add a class method on Volunteer that performs the bulk of the existing task. Add a failing unit test. 

- [x] Fix the code and have the spec pass.

- [x] Call the class method from the rake task.

```
New unhandled error in production from casa in court_report_due_reminder (details)
Unhandled error
NoMethodError: undefined method `court_report_submitted' for #<CasaCase:0x00005573133e44d8>
Did you mean?  court_report_submitted!
              court_report_submitted?
              court_report_submitted_at
              court_report_submitted_at?
              court_report_submitted_at=
              court_report_not_submitted?
              court_report_not_submitted!
              court_report_due_date
              court_report_due_date?
              court_report_due_date=
Location
lib/tasks/court_report_due_reminder.rake:6 - block (3 levels) in <main>
```
**Extra credit**

~~Add a court_report_submitted? method on the casa_case method that returns true if court_report_submitted_at is not nil and court_report_status is something other than not_submitted.~~

~~Modify fix for this task to use court_report_submitted? method as well as change the check for court_report_submitted_at in app/views/casa_cases/show.html.erb to use court_report_submitted?~~

Since #1389 is soon-to-be implemented, just use `court_report_not_submitted?` as the check for these cases ^^

**Comment by notapatch** [comment]
@littleforest with regards to the extra credit `court_report_submitted?` method - as you may be aware the method `court_report_submitted?` is automatically generated by the [Rails enum api](https://api.rubyonrails.org/v6.0.3/classes/ActiveRecord/Enum.html) - which we can see in the "Did you mean?" above. To confirm, did you want to override the enum generated `court_report_submitted?` with our own method?

Otherwise, if you didn't have strong opinion I'd suggest `court_report_filed?` :thinking:

**Comment by littleforest** [comment]
@notapatch yes, you're right about the enum method! 🤦‍♀️ Please don't override that method. `court_report_filed?` sounds great.
