### ISSUE TITLE
Paginate view of Case Contacts

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1502]
### Acceptance Criteria
- [ ] up to 20 `case_contacts` display on a page at once
- [ ] user can click "Next" at the bottom of the page to see more
- [ ] if there are multiple pages of `case_contacts`, then the user can choose which one to click on, like in this example:
< last page 1, 2, 3,...4, 5, 6 next page >

**Comment by scottolsen** [comment]
This looks related to change made in #1485 because we changed it from a `table` to `div`s. I don't have any experience with the [datatables.js](https://datatables.net/) library that is being used but I'm assuming it only works for tables. 

Do we want to revert removing the table or use something like [Kaminari](https://github.com/kaminari/kaminari) for the pagination and try to match the styling?

**Comment by Zrrrpy** [comment]
we definitely don't want to bring the table back, I'll defer to @littleforest or @compwron on recs for accomplishing this while matching the styling. Thank you @scottolsen! We appreciate you and the whole Merchants team! 😄

**Comment by compwron** [comment]
We had a BIG PR recently for making pagination faster. It was more or less instead of using Kaminari. Let me dig it up. I would like to keep what we have? But I could be convinced to move to Kaminari or similar if what we already have doesn't get it done.

**Comment by scottolsen** [comment]
I agree it would be nice to keep things consistent with the pagination but from what I've read about Datatables.js it won't work with the current layout of `case_contacts`. I'm also curious what slowness issues you had with Kaminari?

A few more questions I have about this card. This appears to be a Volunteer only view and the way it's currently setup I think it will be a little weird to have pagination on. Mainly because it's contacts nested in cases. I'm wondering if we need to wait until the tabs are added for each case before this one is completed? Although #735 is closed now so maybe the tabs are a no go?

**Comment by compwron** [comment]
> what slowness issues you had with Kaminari?
We didn't try Kaminari yet

Sorry I was talking about pagination based on a supervervisor/admin viewing all volunteers or all cases etc. :)

**Comment by Zrrrpy** [comment]
just reopened #735 @scottolsen! Not sure why that was closed, but I'm sure @compwron will tell us if there was a reason. 😃 

There are two other places where pagination occurs (@compwron just referenced one of them):
1 - on the "cases" view for `admins` and `supervisors`(https://casa-qa.herokuapp.com/casa_cases)
2 - on the CASA Case Details page viewable by all users. (example: https://casa-qa.herokuapp.com/casa_cases/1187)

Tabs however, will not apply to either of those views.

**Comment by hairedfox** [comment]
> I agree it would be nice to keep things consistent with the pagination but from what I've read about Datatables.js it won't work with the current layout of `case_contacts`. I'm also curious what slowness issues you had with Kaminari?
> 
> A few more questions I have about this card. This appears to be a Volunteer only view and the way it's currently setup I think it will be a little weird to have pagination on. Mainly because it's contacts nested in cases. I'm wondering if we need to wait until the tabs are added for each case before this one is completed? Although #735 is closed now so maybe the tabs are a no go?

Actually there's a lot of issues with Kaminari gem. It's pretty long to explain but I'll put the reference to a benchmark between Kaminari, Will_paginate and pagy (which is my favorite)

https://ddnexus.github.io/pagination-comparison/gems.html

**Comment by compwron** [comment]
https://github.com/rubyforgood/casa/pull/1412

**Comment by compwron** [comment]
@jobannon
