### ISSUE TITLE
RSpec test failed about 117-118 cases when setting up project without Chrome installed

### ISSUE THREAD

**Issue by hairedfox** [rubyforgood/casa#1617]
### Impacted User Types
None

### Environment
Desktop
* OS: macOS
* Version: Mojave 10.14.0

### Current Behavior
When I first cloned the project and followed the guide from the Github repo, everything worked fine. I could run the server and log into the system normally.

But the RSpec failed about 118 cases (sometimes 117)
![image](https://user-images.githubusercontent.com/42526152/105885958-6f819680-603c-11eb-89ba-b02675381fea.png)
![image](https://user-images.githubusercontent.com/42526152/105884760-e158e080-603a-11eb-9cfc-f2dc8410d623.png)

Some sample failed cases:
![image](https://user-images.githubusercontent.com/42526152/105884907-08171700-603b-11eb-97be-245a6ad54050.png)
![image](https://user-images.githubusercontent.com/42526152/105884933-0fd6bb80-603b-11eb-903b-e08a9e169a22.png)
![image](https://user-images.githubusercontent.com/42526152/105884946-15340600-603b-11eb-8cd9-e720ffe8144d.png)

I tried to download the chrome-driver and started it, but there's nothing changed.

There's a case that I saw the message like this: "Can not find Chrome binary". So I tried to install Chrome (currently I'm using Brave as the default browser - which I thought is based on Chromium too 😆  ), but after that all RSpec tests are fine

![image](https://user-images.githubusercontent.com/42526152/105885508-cd61ae80-603b-11eb-89af-81c0eabb228d.png)

### Expected Behavior
When setting up the project for the first time, I think we should mention about install Chrome first, just ChromeDriver maybe not enough. Or in some way get rid of this dependence.

### How to Replicate

1. Using Mac Mojave 10.14.0 without Chrome install (maybe will happen with other OS too)
2. Clone the project and follow the guide
3. Run RSpec to see if it's failed

**Comment by compwron** [comment]
Thank you for opening this issue! I want to fix this.

**Comment by hairedfox** [comment]
@compwron how is this bug going? I saw that it has assigned to no one

**Comment by compwron** [comment]
@hairedfox no contributor has started working on it yet. It is in the To Do list. If you would like to work on it, you can comment "I would like to work on this" and it is all yours :)

**Comment by rpolley** [comment]
Currently running into this too, which is a huge pain because I'm using WSL and the only ways I've found of installing chrome on that are fairly intensive and experimental.

**Comment by rpolley** [comment]
Managed to get chromedriver+chrome up and running on wsl2, however I ran into further issues because webdriver was trying to run a `chromedriver.exe` windows executable file that it had downloaded (never figured out how to get it to not do that, I just replaced it with a symlink to the file I wanted)

**Comment by ATMartin** [comment]
This is an interesting challenge! 🤔 A little quick research suggests Capybara + WSL (v1 _or_ v2) is a known headache, unfortunately. A few options:

- Update docs to highlight the need for Chrome, & link to supporting resources for folks on all major operating systems. _(We should probably do this for now no matter what)_

- Choose an alternative preferred driver (Firefox?) and reconfigure the test suite accordingly. _(I'm not sure this will resolve the headache for Windows folks, and I don't know how this might affect our test accuracy compared to browsers used  by those the app serves 😞 )_ 

- Fall back to an older driver/browser (Qt?) with better platform compatibility, acknowledging that we may have flaky tests as these are mostly deprecated. 😬 

- Replace Chrome-dependent Capybara tests with Cypress specs _(Again, WSL support? Also, relatively sloooow + extra steps. 😢 )_ 

@rpolley I've got a PC but have used WSL sparingly. Any thoughts on what a better Windows-native experience might look like? I'm happy to pair sometime and try some options out!

**Comment by rpolley** [comment]
I'm just going to try using docker for now, since it seems like any native solution would require either getting stuff to work without WSL, or getting Capybara to work with WSL.

**Comment by dcslagel** [comment]
I'm on MacOS and have the same problem as @hairedfox reported it.  (I have Brave(chromium-based) installed also but Capybara/chromedriver aren't configured to find it.   I tested installing chromium-browser with `brew install --cask chromium --appdir ~/Applications`  and that looks like the tests are finding it. However, it failed on 'unidentified developer..'  due to Apple's security quarantine.  So I'm going to install google's Chrome.   That said I have a question. :-)  Is chromedriver needed if Chrome is installed?

**Comment by dcslagel** [comment]
I wondered why the test were passing after I has removed chromedriver.  It turns out that `bundle install` is installing chromedriver in $HOME/.webdrivers via the `webdrivers` gem.  It looks like this is the latest stable version.  So that is why the  tests past after I uninstalled chromedriver and installed Chrome.   From webdriver's README.md it looks like sometimes the web-driver version of chromedriver might not be in sync with the user's installed Chrome and that sometimes that can cause a problem.

**Comment by dcslagel** [comment]
I've created draft pull-request #2258 with updates to the README.md to clarify the setup for Chrome/Chromedriver.  If there is better detail for Linux, Windows and for Windows-Subsystem-for-Linux let me know and I'll add that information.
