### ISSUE TITLE
Remove filters from My Cases view for volunteers

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1701]
![remove-vol-filters](https://user-images.githubusercontent.com/578159/107598714-77603f80-6bd3-11eb-90bf-00a2fc53dad2.png)

**Comment by ErinClaudio** [comment]
@Zrrrpy can I have this!

**Comment by compwron** [comment]
This update caused cases to never show up on the volunteer's dashboard, so I reverted it before the friday deploy. Which is super weird because there IS a test for this and it passes! I suspect the javascript. Let's dig in more this coming week. :) https://github.com/rubyforgood/casa/blob/dbeac18e89d1e6ecaba4c73b02ef5c871cfb15fc/spec/system/dashboard/show_spec.rb#L10

**Comment by ErinClaudio** [comment]
Great, I look forward to it!
