### ISSUE TITLE
Court Report Transitioning Case Detection

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#1996]
### Impacted User Types
volunteers

### Environment
local, QA

### Current Behavior
court reports generate non transitioning elements in the court report template for transitioning cases(gold text)

### Expected Behavior
court reports **do not** generate non transitioning elements in the court report template for transitioning cases(black text only)

### How to Replicate
ex: 
1. - Log into QA as a volunteer.
2. - Click on "Generate Reports" in the left sidebar menu.
3. - Select the transitioning case.
4. - Click "Generate report" at the bottom of the page.

Possibly caused by casa cases without birthdates

**Comment by librod89** [comment]
Is having a case set to `transition` with a nil DOB a valid scenario? 

The dropdown on the "Generate Reports" page will show a case as transitioned according to this method:

```
def has_transitioned?
    transition_aged_youth
end
```

But the report generated will show the gold text according to this method:

```
def in_transition_age?
    birth_month_year_youth.nil? ? false : birth_month_year_youth <= 14.years.ago
end
```

This is what is causing this bug to happen. However, the scheduler that sets `transition_aged_youth=true` only runs for cases where `birth_month_year_youth` is NOT null. Perhaps the cases on staging were created using `db_populator` which sets `transition_aged_youth=random_true_false`?

If these assumptions are correct, I think the way to fix this bug is to run a script in the staging console to set `transition_aged_youth` to false if the `birth_month_year_youth` is nil.

**Comment by compwron** [comment]
> Is having a case set to `transition` with a nil DOB a valid scenario?
Right now yes. We are moving towards only having DOB and deleting the transition flag. 

> The dropdown on the "Generate Reports" page will show a case as transitioned according to this method:
> 
> ```
> def has_transitioned?
>     transition_aged_youth
> end
> ```
> 
> But the report generated will show the gold text according to this method:
> 
> ```
> def in_transition_age?
>     birth_month_year_youth.nil? ? false : birth_month_year_youth <= 14.years.ago
> end
> ```
> 
> This is what is causing this bug to happen. However, the scheduler that sets `transition_aged_youth=true` only runs for cases where `birth_month_year_youth` is NOT null. Perhaps the cases on staging were created using `db_populator` which sets `transition_aged_youth=random_true_false`?
Yes, assume that staging data is seed data. We can update the seeder and re-seed qa/staging (but not prod!)

> If these assumptions are correct, I think the way to fix this bug is to run a script in the staging console to set `transition_aged_youth` to false if the `birth_month_year_youth` is nil.
Sounds great! Can you write that as an after_party rake task?
And let's also update the seeder so we don't redo it...

**Comment by librod89** [comment]
Will do 👍
