### ISSUE TITLE
Add a Way to Assign Multiple Volunteers at Once

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2523]
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, volunteers must be assigned to supervisors one at a time. We would like to make a way for multiple volunteers to be assigned to a supervisor at a time. 

Please refer to the Figma file to see how the UI should look and how the UX should function. The below acceptance criteria represent this same behavior in checklist form.

Figma
[Figma link](https://www.figma.com/file/wRUtmMJCAFdfkUV5JWGu3V/R4G---CASA---Bulk-Actions?type=design&node-id=92%3A6669&mode=design&t=OkMwoBGKhmSdk6rA-1)
PS: Log into Figma to leave comments, and Mallory (our design lead) will respond to them!
 

**Acceptance Criteria**
Table overview

- Assume all table UI and dimensions remain the same unless otherwise noted
- Bottom border of each row spans the table
- Add checkboxes on the left of each row
- Change the “Extra Languages” header to “Additional Languages”
- Move pagination items to the bottom of the table and change all text to “Content 3” text style and update wrap of right pagination item
- Remove “Responsive Data Table” heading
- Change search bar font to “Content 1” text style
- When screen width is 1024px or below, remove the checkbox column and related functionality
 
Row checkbox functionality

- The default state is that the check box is unselected
- On row hover, shadow appears behind row (see https://demo.plainadmin.com/task for reference)
- On box click, highlight row with color and change checkbox to blue box with white checkmark
- When at least one but not all checkboxes have been clicked, change header checkbox to blue box with white line
- When at least one checkbox has been selected display “Manage Volunteer” button above table (update number and add or remove “s” after “Volunteer” to match number of selected boxes)
- When checkbox on header row is selected, check all checkboxes in the table
- When checkbox on header row is deselected, uncheck all checkboxes in the table
- When any checkboxes are unselected return row to default state
 
Manage Volunteers Button (On-click)

- When “Manage Volunteers” button is selected display a modal and page backdrop
- On hover of dropdown in modal, outline the dropdown box in colored border
- On click, display names of all supervisors and a “None” option
- On hover in the dropdown list, highlight hovered item in blue
- On click, display a checkmark on the left of selection, close dropdown, and display selection in place of “Choose a supervisor”
- When dropdown is open, after a selection is made, and without hover, selected item returns to original color and continues to display checkmark
- When "Cancel" or "X" is selected in modal, close modal and backdrop and return to original screen while maintaining row selections
- On click of “Confirmation,” close modal, reflect changes in Volunteers table:
If "None" is selected from dropdown and confirmed, update each selected Volunteer’s Supervisor to unassigned/empty
Otherwise, update Supervisor for each Volunteer to selected Supervisor
- References:
Modal reference is “Modal 3” at following link: https://demo.plainadmin.com/modals.html
Dropdown reference is on “Selects” card at the following link: https://demo.plainadmin.com/form-elements.html

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

**Comment by compwron** [comment]
This does not seem to be an urgent ask

**Comment by JoshDevHub** [comment]
I'd like to work on this one.

**Comment by elhalvers** [comment]
Still working on this. Finished the feature and have finished the request
test. Working on the system test now.

: )

**Comment by MalloryPriceDesign** [comment]
hey @elhalvers, thanks for working on this! @bcastillo32 and I have just finalized the design for this functionality! Please see below for how to implement the UI and let me know if you have any functions!


# Bulk Actions: Assign/Unassign Volunteers
 
Please refer to the Figma file to see how the UI should look and how the UX should function. The below acceptance criteria represent this same behavior in checklist form. [Figma link](https://www.figma.com/file/wRUtmMJCAFdfkUV5JWGu3V/R4G---CASA---Bulk-Actions?type=design&node-id=92%3A6669&mode=design&t=OkMwoBGKhmSdk6rA-1 
)

**PS:** Log into Figma to leave comments, and I will respond to them!
 
 
## Acceptance Criteria
 
**Table overview**
- Assume all table UI and dimensions remain the same unless otherwise noted
- Bottom border of each row spans the table 
- Add checkboxes on the left of each row
- Change the “Extra Languages” header to “Additional Languages”
- Move pagination items to the bottom of the table and change all text to “Content 3” text style and update wrap of right pagination item
- Remove “Responsive Data Table” heading
- Change search bar font to “Content 1” text style
- When screen width is 1024px or below, remove the checkbox column and related functionality 
 
**Row checkbox functionality** 
- The default state is that the check box is unselected 
- On row hover, shadow appears behind row (see https://demo.plainadmin.com/task for reference)
- On box click, highlight row with color and change checkbox to blue box with white checkmark
- When at least one but not all checkboxes have been clicked, change header checkbox to blue box with white line
- When at least one checkbox has been selected display “Manage Volunteer” button above table (update number and add or remove “s” after “Volunteer” to match number of selected boxes)
- When checkbox on header row is selected, check all checkboxes in the table
- When checkbox on header row is deselected, uncheck all checkboxes in the table 
- When any checkboxes are unselected return row to default state
 
**Manage Volunteers Button (On-click)**
- When “Manage Volunteers” button is selected display a modal and page backdrop
- On hover of dropdown in modal, outline the dropdown box in colored border 
- On click, display names of all supervisors and a “None” option
- On hover in the dropdown list, highlight hovered item in blue
- On click, display a checkmark on the left of selection, close dropdown, and display selection in place of “Choose a supervisor”
- When dropdown is open, after a selection is made, and without hover, selected item returns to original color and continues to display checkmark 
- When "Cancel" or "X" is selected in modal, close modal and backdrop and return to original screen while maintaining row selections 
- On click of “Confirmation,” close modal, reflect changes in Volunteers table:
- If "None" is selected from dropdown and confirmed, update each selected Volunteer’s Supervisor to unassigned/empty
- Otherwise, update Supervisor for each Volunteer to selected Supervisor
- References:
  -  Modal reference is “Modal 3” at following link: https://demo.plainadmin.com/modals.html
  - Dropdown reference is on “Selects” card at the following link: https://demo.plainadmin.com/form-elements.html

**Comment by bcastillo32** [comment]
@MalloryPriceDesign these look great! @elhalvers and/or @ShamiTomita please refer to the designs and acceptance criteria and reach out if you have any questions :)

I created a new issue a while back before I saw this one (https://github.com/rubyforgood/casa/issues/4873) I can delete tho

**Comment by elhalvers** [comment]
Thanks @MalloryPriceDesign and @bcastillo32 !! 🥳😄

**Comment by elhalvers** [comment]
I am adding @jamgar to help with this issue/project. James is also with AOL and has been doing some awesome CASA work! @ShamiTomita and I have been selected as the junior leads to build the Rails World Conference app which will take a bit of my active attention and focus so I am happy to bring on James for additional help on this! : )

**Comment by bcastillo32** [comment]
@elhalvers great! @jamgar happy to continue working with you! :)

**Comment by elhalvers** [comment]
🙌 😃

**Comment by compwron** [comment]
This is the same as https://github.com/rubyforgood/casa/issues/4873 ??

**Comment by elhalvers** [comment]
> This is the same as #4873 ??

It looks like it! : )

**Comment by bcastillo32** [comment]
yes, they are the same. I didn't find this one when I made #4873

**Comment by littleforest** [comment]
@bcastillo32 can you close one of these tickets? Not sure which one is better described.

**Comment by bcastillo32** [comment]
> @bcastillo32 can you close one of these tickets? Not sure which one is better described.

done. I closed the other one.

**Comment by jamgar** [comment]
Update: Making progress on this. I had a blocker with not knowing JQuery Datatable which is used to give the table sort/filter capabilities. They have a checkbox extension that I added to give the functionality for select/unselect all.

**Comment by jamgar** [comment]
Hi @bcastillo32 this is completed with one exception, which is I could not get the box shadow to work on hover of row. Instead I added a background color change on hover so we could get this feature completed. Any attempt to get the correct shadow effect was not working. I am not sure why but suspect that the way the tables are being created it is taking precedence on the styles. The project is using jquery datatables plugin which auto generates the tables on page request. As a side note, what I have found durning my research is that under normal circumstances adding box shadow to a table element can be a bit of a hack. If this is a hard set requirement then I would recommend opening another issue to address just the that style so that someone with CSS ninja skills :D can help. 

Please see PR https://github.com/rubyforgood/casa/pull/5144

**Comment by gorangorun** [comment]
Can i take it?

**Comment by bcastillo32** [comment]
> Can i take it?

Hi @gorangorun we have a PR for this already bu thank you for the offer - we have some other tickets that could use some love :)

**Comment by schoork** [comment]
I think this has been solved.
