### ISSUE TITLE
Fix skipped test when a volunteer has been reassigned to a new supervisor

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2621]
**Description**
supervisor_mailer/weekly_digest when a volunteer has been reassigned to a new supervisor
     # Temporarily skipped with xit
     # ./spec/views/supervisor_mailer/weekly_digest.html.erb_spec.rb:78

**Existing gem(s), file(s) needing updating, changing or deleting**

**New file(s) needing creating**

**Comment by matisnape** [comment]
Hi, what's the expected behaviour here really? 
Judging by the code, the only thing that has to be asserted in this test is that there's no `(not assigned to a new supervisor)` text, but there another test that checks that. I don't get the the differences between logic behind those 3 cases https://github.com/rubyforgood/casa/blob/6adb2631df3f359205561dc333b371a2cb797270/spec/views/supervisor_mailer/weekly_digest.html.erb_spec.rb#L65-L118

**Comment by compwron** [comment]
This test may be entirely obsolete. Please read the test and the surrounding tests and make a PR either making the test useful, or removing the not useful test :)
