### ISSUE TITLE
Make case contact save errors red

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#267]
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer / all

**Description**
Make these errors visible and red + highlight which fields need fixing- with a red outline

**Screenshots of current behavior, if any**
![Screen Shot 2020-05-16 at 4 07 09 PM](https://user-images.githubusercontent.com/578159/82131951-778bf580-978f-11ea-9d8e-a10dc0c2de3e.png)

**Comment by marcelkooi** [comment]
@compwron Hi there, I looked into this by visiting the `/case_contacts/new` page and submitting an empty form but I'm getting a different error in the [cases contact controller](https://github.com/rubyforgood/casa/blob/master/app/controllers/case_contacts_controller.rb#L80) since `params[:case_contact][:casa_case_id]` is nil.

I don't know enough about the app yet to determine what all needs to be fixed. A quick fix would be to have something like `(params[:case_contact][:casa_case_id] || {})` but when I try that, I don't see any errors and nothing is created (but a success notification appears).

Do you know if we need to add any other validations or change some logic in the controller?

**Comment by compwron** [comment]
It sounds like you have somehow managed to open the Create Case Contact page for a volunteer with no case. This is a bug and I've created a github issue for it here- please add details of how you did it :) https://github.com/rubyforgood/casa/issues/268

In order to replicate this bug, make sure that you are logged in as a user which has at least one case_assignment. In order to set this up in the commandline, you can do something like:
```
```

**Comment by marcelkooi** [comment]
Have a screenshot here to explore different options.

1. Do we want to make the labels red? And if so, should we make them bold like "Contact types"?
2. Should we add a red box shadow to the checkbox inputs? (as shown on the Youth checkbox)
3. Do we want to add a red box shadow to the text inputs or a red border? (red border shown for occurred_at)

![screencapture-localhost-3000-case-contacts-2020-05-17-22_04_35](https://user-images.githubusercontent.com/13142719/82167637-71c70a80-988a-11ea-9fef-6e08b7b2a4ac.png)

**Comment by compwron** [comment]
This looks great! It's a big improvement :) ✨🚀

As with many UI decisions on this project, the only guidance we have is "use your best judgement, our stakeholders like most things. Where possible, keep it simple." :) 💖
