### ISSUE TITLE
Download Mileage report button only works once per page load

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2721]
### Impacted User Types
 - supervisors
 - admins

### Environment
all

### Current Behavior
The download mileage report button only lets you click it once before being disabled
![image](https://user-images.githubusercontent.com/8918762/136808767-0767d5dc-6b60-491b-bbf7-91e50dc62cb3.png)

### Expected Behavior
Multiple mileage report downloads should be allowed

### How to Replicate
 - Sign in to the website as a supervisor or admin
 - Click "Export Data" in the side bar or visit /reports
 - Click Mileage report
 - The button cannot be clicked again

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
I think disabling the button for a short time is a common behavior. I don't think clicking a button and having it disabled until you refresh is common.

**Comment by ludamillion** [comment]
I can work on this.

**Comment by ludamillion** [comment]
@compwron I'm having a heck of a time trying to write a spec for this. I was writing it in Cypress since that seems like the right place but Cypress doesn't seem to handle the way the report page produces a csv file that needs to be handled by the browser correctly. I'm going to put this on the back burner for a little bit. Maybe I'll ask on the Slack if there is anyone who knows more about Cypress can assist.

**Comment by compwron** [comment]
I hope that a capybara test with `js: true` would be able to test this behavior. If you're around tonight for office hours, let's pair on it :)
(office hours are weds 6-8pm pacific, zoom link in slack)
If not, we can merge without if we need to and file a chore ticket to come back to it
