### ISSUE TITLE
Fix azure

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3224]
see slack https://rubyforgood.slack.com/archives/CVB0QJGVD/p1645213440480059

**Comment by compwron** [comment]
no action currently known needed

being able to see what is in our azure account would be nice tho
court report templates, gen erated court reports, ?

**Comment by compwron** [comment]
figure how much storage we have...

**Comment by elasticspoon** [comment]
Doesn't seem like we need to do anything. Slack thread with context:


Retirement of superseded Azure AD (Azure Active Directory) Connect Sync versions
MC333227 · CASA PRINCE GEORGE’S COUNTY
We will begin retiring past versions of Azure Active Directory (Azure AD) Connect Sync 12 months from the date they are superseded by a newer version.
Key points
Timing: In mid-March 2023, this policy will go into effect, and all versions prior to the last released version (latest version prior to mid-March 2022) will retire.
This policy does not change the retirement of all 1.x versions of Azure AD Connect Sync on August 31, 2022, which is due to the retirement of the SQL Server 2012 and Azure AD Authentication Library (ADAL) components.
Action: If you are not already using the latest release version of Azure AD Connect Sync, you should upgrade your Azure AD Connect Sync software before 12 months elapses from the date they were superseded by the newest version.
Roll-out: tenant level
How this will affect your organization:
If you run a retired version of Azure AD Connect, it might unexpectedly stop working. You also might not have the latest security fixes, performance improvements, troubleshooting and diagnostic tools, and service enhancements.
Frequently Asked Questions:
Q: If I do not upgrade will I no longer be eligible for support?
A: We will always try to help, but if you rely on a retired version of Azure AD Connect Sync then we may not be able to provide you with the support experience your organization needs. So, it is important to stay current.
Q: Will my retired version of Azure AD Connect Sync stop working after 15 March 2023?
A: Probably not – although retired versions may rely on services and software that may no longer be available or might stop working after that date. So, it is important to say current.
Q: Are there functional differences between my version in use and the latest released version?
A: Depending upon the version from which you are upgrading, there may be security improvements, bug fixes, and functional enhancements. You can review changes by feature on the Azure AD Connect: Version release history page.
What you need to do to prepare:
To upgrade your Azure AD Connect Sync server you can follow the steps that are given here: Azure AD Connect: Upgrade from an earlier version.
If you have any concerns about the retirement of superseded versions of Azure AD Connect Sync or have questions about upgrading to the latest version, please open a support request, mentioning “Directory Synchronization – Azure AD Connect” as your support topic.
Learn more:
Retiring Azure AD Connect 2.x versions
Additional Information
View this message in the Microsoft 365 admin center


Linda (she/her) - CASA and Flaredown
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-version-history#retiring-azure-ad-connect-2x-versions


Linda (she/her) - CASA and Flaredown
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-upgrade-previous-version
docs.microsoft.comdocs.microsoft.com


Linda (she/her) - CASA and Flaredown

Microsoft Azure
Azure Storage TLS Changes for Root and Intermediate Certificate Authorities
This message is to inform you that Azure Storage TLS server certificates will be issued by new Root and Intermediate Certificate Authorities starting July 2022, postponed from February 2022. Azure Storage services will be chained to DigiCert Global G2 Root, and the TLS server certificates will be issued by new ICAs.
This change is being made because the current “Baltimore CyberTrust Root” will expire in May 2025.
Will there be any impacts to my system?
We expect that most Azure Storage customers will not be impacted. However, if you explicitly specify a list of acceptable CAs (a practice known as “certificate pinning”), your application may be impacted and immediate action is required.
Do you have more information available about the impending changes?
Yes, please read the following storage blog, which includes additional information about these changes:
Azure Storage TLS: Critical changes are almost here! (…and why you should care)
Account Information
Subscription ID: C1881BD0-D424-49D9-ACCD-55B186B8BF9C


Linda (she/her) - CASA and Flaredown
https://techcommunity.microsoft.com/t5/azure-storage-blog/azure-storage-tls-critical-changes-are-almost-here-and-why-you/ba-p/2741581


Linda (she/her) - CASA and Flaredown
  2 years ago
```yml
microsoft:
  service: AzureStorage
  storage_account_name: <%= ENV['STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  container: <%= ENV['STORAGE_CONTAINER'] %>
```


Linda (she/her) - CASA and Flaredown
`gem "azure-storage-blob", require: false`


Linda (she/her) - CASA and Flaredown
  2 years ago
https://rubygems.org/gems/azure-storage-blob
VERSIONS:
2.0.3 - December 06, 2021 (38 KB)


Michaela
Linda and I took a look at this and whatever it is it doesn't appear to be urgent, so let's not worry about it until at least March.


Linda (she/her) - CASA and Flaredown
https://github.com/rubyforgood/casa/pull/1528


Richard
These still a thing?

Linda (she/her) - CASA and Flaredown
Hi! When we read thru the azure docs and blogs, it seems like this is the early warning of a change scheduled some time in the future and there is not action we need to take right now. We store less than 10 files in azure right now afaik, but I don't have login creds other than the api token used in the prod app


Richard
Hi Linda, they do like to give a good amount of notice don't they! Certainly doesn't sound like AD connect will be an issue for you.  Can't see anything being pinned so suspect the storage is fine, MS seem to offer a test storage account before June 22 to confirm.  As you say not too urgent!

Happy to help if I can, work as an Azure DevOps engineer, more Ops side but can read Ruby well enough so looking for something to help with :grinning:


Linda (she/her) - CASA and Flaredown
yay! good to know :slightly_smiling_face:
