### ISSUE TITLE
☂️ Individualized Education Plans

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#3276]
## What type(s) of user does this feature affect?
 - volunteers
 
## Description
See comments

## QA Login Details
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422020162899?thread_ts=1646419820.956659&cid=CVB0QJGVD)
SB: bigger idea… IEPs
individualized education plans

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422084282459?thread_ts=1646419820.956659&cid=CVB0QJGVD)
SB: IPE
cmplicated, federal
foster parents cant sign, casa worker cant sign, parent or parent surrogate has to sign- offical, apointed by board of education, training, ediucation, Big Thing Role
school cannot have a legally binding IE meeting w/o that person…

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422126595099?thread_ts=1646419820.956659&cid=CVB0QJGVD)
SB” I saw to volunteer, for case, when IEP need to contact school and see who is on distro list for IEP meetings, becase otherwise cant have meeting  no parents
two week, meetings where havent done that work, waste time, grrr

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422185091939?thread_ts=1646419820.956659&cid=CVB0QJGVD)
huge and tricky, another system, not great training in IEPs, developerin a training for IEPs
(should we track if a case has an IEP?)
can integrate with training, some kind of roadmap “kid has IEP? click button” take u to site with steps 1. review who invited
then video of Andrea saying… here is an IEP, here is where to look..
basically a checklist like emancation

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422194551049?thread_ts=1646419820.956659&cid=CVB0QJGVD)
“choose ur own adventure” thru IEP (FD laughs)

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422209839509?thread_ts=1646419820.956659&cid=CVB0QJGVD)
IEP federal… could scale to everywhere? also state regulations for this tho

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422274842299?thread_ts=1646419820.956659&cid=CVB0QJGVD)
JH: docuhub???
SB: no idea

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422316638659?thread_ts=1646419820.956659&cid=CVB0QJGVD)
don’t want IEPs IN the system, want an interactive guide to looking at the IEP…

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422472310589?thread_ts=1646419820.956659&cid=CVB0QJGVD)
JH: left nav bar, add learnign hours and also Resources
(am am skeptical, having never liked a Resources ab myself)
maybe just IEP

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422480154679?thread_ts=1646419820.956659&cid=CVB0QJGVD)
“the grat thing is one crntral location to access things”

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422508498819?thread_ts=1646419820.956659&cid=CVB0QJGVD)
JH; we have training videos, can we add links to youtube for all our stuff

[Linda (she/her) - CASA and Flaredown](https://app.slack.com/team/UTSG40QCW)  [4 days ago](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1646422540570149?thread_ts=1646419820.956659&cid=CVB0QJGVD)
I wonder if we could make a per-org “resources
 field for admins to edit

**Comment by compwron** [comment]
https://www.californiaspecialedlaw.com/individual-education-plan-iep

related to per org resources field

"this child has an IEP" button or checkmark which unlocks something like but different the Emancipation checklist

**Comment by elasticspoon** [comment]
closing in favor of https://github.com/orgs/rubyforgood/projects/15/views/1?pane=issue&itemId=65025264
atm this is not a coherent ask
