### ISSUE TITLE
Add Supervisor view to Admin dashboard

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#360]
Part of epic #4

**What type of user is this for? [admin/volunteer/supervisor/all]**
admin

**Where does/should this occur?**
At the very bottom of the admin dashboard, underneath the Cases view.

**Description**
Admins should be able to view all supervisors at a glance, much like they can view volunteers and cases in their dashboard. 

Columns to display should include:
- Supervisor Name [Display as: Supervisor Name]
- Number of Volunteer Assignments [Display as: Volunteer Assignments]
- Number of Volunteer Assignments serving Transition Aged Youth [Display as: Serving Transition Aged Youth]
- Number of Volunteer Assignments who have not logged a case contact in two weeks or more [Display as: No Contact]
- Edit [Display as: Actions]

**Screenshots**
It should look something like this, but with different columns.
<img width="1375" alt="supervisor can view all volunteers" src="https://user-images.githubusercontent.com/62810851/84725070-991eff00-af3e-11ea-9828-de19b644da32.png">

**Comment by armahillo** [comment]
Some questions:

For dev team: 
> Number of Volunteer Assignments [Display as: Volunteer Assignments]
Would it be OK to do a counter cache for this, to have the data onhand?

> Number of Volunteer Assignments serving Transition Aged Youth [Display as: Serving Transition Aged Youth]
Same thing -- counter cache ok?  Alterantely: can we do a background job to calculate it? I've not looked in to how this would be calculated

> Number of Volunteer Assignments who have not logged a case contact in two weeks or more [Display as: No Contact]

Do we have the ability to run background jobs, because I think that's how we should do this. 

I found a few 508 / a11y issues, would it to create issues for them in GH?

**Comment by compwron** [comment]
@armahillo Let's do the number of volunteer assignments inline for now as a sql query or similar. We don't currently have any background jobs. This app is going to be deployed on heroku, and will be spun down quite often- so anything relying on caching will make the app slower to start. Since the aggregate metrics are only going to be used for our ~5 supervisor/admins (as compared to our 200+ volunteers) our stakeholders have requested that we prioritize the volunteer experience wherever possible. 

Yes please do open issues for 508 / a11y issues :) Thanks!

**Comment by compwron** [comment]
@armahillo Hey just checking in, this is marked as "in progress" how is it going? If you want to pair program we're on zoom today 1-230pm pacific time, and I'm happy to hang out other times too. You can join us in ruby4good slack at #casa https://rubyforgood.herokuapp.com/

**Comment by Zrrrpy** [comment]
@armahillo - Sounds like @compwron is going to pick this up. Feel free to dive into another issue if you're still interested and have some time, and if you want to hop back into this one let us know!
