### ISSUE TITLE
Fix New Case Contact CSS issue

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#387]
the checkboxes should not overlap the text
![Screen Shot 2020-06-24 at 9 04 26 AM](https://user-images.githubusercontent.com/578159/85590975-b9fbea00-b5f9-11ea-89a3-a8ad8121209d.png)

**Comment by rjbeers** [comment]
I'm pretty sure this is because both bootstrap 3 and bootstrap 4 css are loaded onto all pages. I am not familiar with the app, so I am not well equipped to regression this this, but  https://github.com/rubyforgood/casa/blob/f87ee830c12e434c35ece5c09c11f1fabb6c9733/app/views/layouts/application.html.erb#L8 should be removed, and styles should generally be fixed.
