### ISSUE TITLE
[bug] Unassign Volunteer button should be present for all volunteers

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#447]
https://casa-r4g-staging.herokuapp.com/casa_cases/903/edit
<img width="1091" alt="Screen Shot 2020-07-26 at 10 10 20 AM" src="https://user-images.githubusercontent.com/578159/88485093-4d417b80-cf28-11ea-93be-a9c09a0b4317.png">
<img width="1053" alt="Screen Shot 2020-07-26 at 10 10 13 AM" src="https://user-images.githubusercontent.com/578159/88485096-503c6c00-cf28-11ea-8317-3f03d35df86b.png">

**Comment by cliftonmcintosh** [comment]
The problem isn't that newly assigned volunteers don't have an "Unassign Volunteer" button. This occurs when the person doing the editing is a supervisor and the newly assigned volunteer is supervised by someone else. The problem is that the volunteer is supervised by someone else. If the newly assigned volunteer is supervised by the person editing, then the button shows up.

If the person editing is a casa admin, then this behavior doesn't happen because a casa admin can unassign volunteers regardless of who is supervising them. If the person editing is a supevisor, then the supervisor can only unassign someone that that supervisor supervises.

Here is where that logic is defined: https://github.com/rubyforgood/casa/blob/master/app/views/casa_cases/_volunteer_assignment.html.erb#L28-L32

Here are screenshots showing this behavior.

## Admin can always unassign volunteer
Admin has just assigned Allan Sauer and Armand Boyle to this case. Note that the Unassign Volunteer button is active.
![after-admin-adding-a-volunteer](https://user-images.githubusercontent.com/3824492/88488765-f30adf80-cf54-11ea-9c5c-50a6c8a0182f.png)

## Supervisor is restricted to unassigning a volunteer that the supervisor supervises
Here is a screenshot of supervisor "supervisor1@example.com" editing a case. Note that the supervisor can only unassign one of the volunteers because the other volunteers are supervised by someone else.

Here are the assignments
```sql
casa_development=# select v.display_name as "volunteer name", s.email as "supervisor email", s.display_name as "supervisor name" from users v join supervisor_volunteers sv on v.id = sv.volunteer_id join users s on s.id = sv.supervisor_id where v.display_name in ('Dudley Grant PhD', 'Dennis Kerluke LLD', 'Alline Maggio MD');
   volunteer name   |       supervisor email       |  supervisor name  
--------------------+------------------------------+-------------------
 Dudley Grant PhD   | dvm_claudewaters@example.com | Claude Waters DVM
 Dennis Kerluke LLD | supervisor1@example.com      | Gloria O'Malley
 Alline Maggio MD   | robbiehilpert@example.org    | Robbie Hilpert
(3 rows)
```
Here is the screenshot.
![supervisor-assigns-volunteer-supervisor-does-not-supervise](https://user-images.githubusercontent.com/3824492/88488851-d8853600-cf55-11ea-8931-4dccc1403eea.png)

**Comment by compwron** [comment]
Makes sense, thanks!

**Comment by cliftonmcintosh** [comment]
Does the business rule as it is now remain, or should it be changed so that any supervisor can unassign any volunteer?

If the business rule remains, then the behavior described here will remain. If different behavior is desired, then I believe the way to change the behavior would be to allow any supervisor to unassign any volunteer, not just the volunteers they supervise.

**Comment by compwron** [comment]
Yes, let's have the supervisor be able to un/assign any volunteer.

**Comment by Zrrrpy** [comment]
Thank you @compwron and @cliftonmcintosh!
