### ISSUE TITLE
volunteer un/assignments on the edit supervisor page should behave the same way as on edit CASA case page

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#449]
Part of epic #105 

**What type of user is this for? [admin/volunteer/supervisor/all]**
supervisors

**Where does/should this occur?**
On the <a href="https://casa-r4g-staging.herokuapp.com/supervisors/793/edit">edit supervisor page</a>

**Description**
Previously assigned (unassigned) volunteers should display on Edit Supervisor pages just like they display on Edit CASA Case pages. 
_Current behavior:_ A volunteer disappears from a supervisor's page after unassigning them. 
_Intended behavior:_ An unassigned volunteer should still show on a supervisor's page, as "unassigned". 

**Screenshots**
This is what it looks like:
![Screen Shot 2020-07-26 at 11 06 44 AM (2)](https://user-images.githubusercontent.com/62810851/88486125-60f0e000-cf30-11ea-994d-6b14d34d1773.png)

This is what it should look like:
![Screen Shot 2020-07-26 at 11 07 41 AM (2)](https://user-images.githubusercontent.com/62810851/88486128-66e6c100-cf30-11ea-8d4f-4873d5711133.png)

Relates to issue: #447

**Comment by compwron** [comment]
This will require adding a new db column is_active to supervisor_volunteers table

**Comment by cliftonmcintosh** [comment]
The list of volunteers on that page is a list of all of the volunteers assigned to that supervisor. Once a volunteer has been unassigned from a supervisor, that relationship is gone. I don't believe there is anything in the current data model that keeps track of a former association.

One approach would be to add some sort of active flag to the `supervisor_volunteers` table that would allow tracking of that relationship. Then, instead of deleting a record when a volunteer is unassigned from a supervisor, you would set the flag to false.

**Comment by compwron** [comment]
@cliftonmcintosh I agree, we're going to need to change the data model a bit to do this. Adding an active flag seems like the correct way for now- ideally the column name and implementation will be similar to how volunteer assignments do it. :)

**Comment by cliftonmcintosh** [comment]
What is the expectation when:

- a volunteer is assigned to supervisor A
- the volunteer is unassigned to supervisor A
- the volunteer is assigned to supervisor B

It would be easiest if the same `supervisor_volunteers` relationship could be re-used, replacing the supervisor id with supervisor B's id.
If we don't do that, I believe we will have to change the relationship  from many to one to many to many.

**Comment by compwron** [comment]
@cliftonmcintosh I'm not sure I understand the question. I think we will need to have an `active` flag on `supervisor_volunteers` relationship and also allow a volunteer to have multiple records in `supevisor_volunteers` but only one active record at once.  :)

**Comment by cliftonmcintosh** [comment]
@compwron

#563 has taken the approach of removing any old, inactive `supervisor_volunteer` associations when a new one has been established. If maintaining the old inactive associations is needed, then #563 will not fulfill that need.

**Comment by compwron** [comment]
@cliftonmcintosh Yes, we want to keep the old inactive associations. #563 is a good step forward but not a complete solution. Sorry about the confusion. You rock!

**Comment by compwron** [comment]
I reopened this issue after merging https://github.com/rubyforgood/casa/pull/563 auto-closed it because of the above conversation- like @cliftonmcintosh said, we also want to keep the old inactive associations. Which is more work! I think that #563 is a meaningful and valuable addition of functionality so I merged it :)

**Comment by cliftonmcintosh** [comment]
@compwron

Thank you. Because I am not sure I will have the bandwidth to address this issue fully in the next week or so, I will unassign myself and move this issue back to "To do". That will allow someone else to pick it up if they have the bandwidth. If it is not addressed by someone else before I have the bandwidth, I will be happy to take it up again.

**Comment by compwron** [comment]
Sounds good! You rock :)

**Comment by cliftonmcintosh** [comment]
For anyone who might pick this up, here is what I believe is left:

- The layout is wrong. There should be Status and Actions columns, not just an Actions column that serves two purposes.
- When a volunteer is unassigned from one supervisor and then assigned to another, the first `supervisor_volunteer` relationship should not be deleted. It should remain. This will require a many-to-many relationship between volunteers and supervisors, not the existing many-to-one relationship. Any use of `Volunteer.supervisor_volunteer` will need to be updated to be `Volunteer.supervisor_volunteers`.
- The scope `User.volunteers_with_no_supervisor` will need to be updated so that it can handle the many-to-many relationship and accurately define which volunteers currently have no active association with a supervisor.

**Comment by cliftonmcintosh** [comment]
I've played around a little with this. One problem I've encountered is that I don't believe we can do this:

```ruby
  has_many :supervisor_volunteers, foreign_key: "supervisor_id"
  has_many :volunteers, -> { order(:display_name) }, through: :supervisor_volunteers

  has_many :supervisor_volunteers, foreign_key: "volunteer_id"
  has_many :supervisors, through: :supervisor_volunteers
```

We can't declare the `has_many :supervisor_volunteers` relationship twice.

Any suggestions for an alternative?

**Comment by compwron** [comment]
@cliftonmcintosh that's a good question. Maybe @abachman or @armahillo have some thoughts on how to do the double-ended many to many in rails?

**Comment by compwron** [comment]
Please avoid working on this until #624 is merged

**Comment by littleforest** [comment]
@compwron so should we be removing [this code](https://github.com/rubyforgood/casa/blob/master/app/controllers/supervisor_volunteers_controller.rb#L10-L13) that deletes all previous supervisor/volunteer relationships?

```
# app/controllers/supervisor_volunteers_controller.rb

    SupervisorVolunteer
      .where(volunteer_id: supervisor_volunteer.volunteer, is_active: false)
      .where.not(supervisor_id: supervisor_volunteer.supervisor.id)
      .destroy_all
```

**Comment by compwron** [comment]
@littleforest Yes, either now or eventually we need to get rid of that. I'm worried it may break other things which use `volunteer.supervisor` or `supervisor.volunteers` - we need to make sure that `supervisor_volunteer` records with `is_active=false` are filtered out in some way (default scope, explicit scope, or other filter). 
I would prefer to not have default filters because it can be hard to know that they're there, but I'm open to discussion :)

**Comment by cliftonmcintosh** [comment]
@littleforest 

Thank you for taking a look at this issue. The `destroy_all` cannot be removed until the volunteer-to-supervisor relationship has been turned into a many-to-many relationship. Removing that delete will cause problems as long as the volunteer-to-supervisor relationship is many-to-one. 

If the delete is removed before altering the relationship, things will break.
