### ISSUE TITLE
[bug] Error when admin adds new volunteer

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#450]
Part of epic #4

**What type of user is this for? [admins/supervisors/volunteers/all]**
admins

**Where does/should this occur?**
<a href="https://casa-r4g-staging.herokuapp.com/volunteers/new">create new volunteer page</a> – accessed by clicking "new volunteer" from the admin dashboard

**Current behavior**
After an admin clicks "create user," they get an error page. If you navigate back from that error page, you either get a second error message that says user was not created because email already exists (even when it doesn't) OR the page appears as though nothing has been saved. Then, if the admin returns to the dashboard and refreshes the page, the newly created user will appear if you search for them. 

**Intended behavior**
After an admin clicks "create user," they should see a success message, such as "user successfully created!" and then have the option to return to dashboard or create new user. They should _not_ be navigated away from this page after a new user is successfully created. 

**Screenshots**
First error message
![Screen Shot 2020-07-26 at 11 21 20 AM (2)](https://user-images.githubusercontent.com/62810851/88486629-e033e300-cf33-11ea-8089-d871910a2b99.png)

**Comment by Zrrrpy** [comment]
<img width="686" alt="Screen Shot 2020-07-26 at 11 36 13 AM" src="https://user-images.githubusercontent.com/62810851/88486664-46206a80-cf34-11ea-823a-1f2b758b6945.png">

Looks like this may be related to adding @example.com emails to new volunteers?

**Comment by lauramosher** [comment]
I'll take this one! :)

**Comment by lauramosher** [comment]
Hi!

So I dug into this a short bit and I was unable to produce this issue locally — the mail sent as expected. I was able to reproduce this issue on the Staging link provided.

Based on the error message provided "Please add your own domain or add the address to authorized recipients in Account Settings" and the documentation here:

> This domain is to be used for testing only. It allows both sending and receiving messages; and also tracking can be enabled for it. But it only allows sending to a list of up to 5 authorized recipients. 

My guess is that it's erroring due to the email being provided for the Volunteer is not on the Mailgun sandbox "authorized" email list. I would suggest adding an authorized email to your account and seeing if the error persists.

**Comment by Zrrrpy** [comment]
Just tried it with a @gmail address, which I will assume is on the authorized list and got the same error.

**Comment by lauramosher** [comment]
@Zrrrpy I think, based on the [documentation](https://help.mailgun.com/hc/en-us/articles/217531258-Authorized-Recipients), it sounds like it'll a specific set of 5 authorized email addresses rather than a blanket authorized domain. So the specific gmail email address would need to be on the authorized list, rather than the whole @gmail.com domain.

There might be a way to add and "verify" a `casa` owned domain as being authorized, which may be a worthwhile route. I'm not sure of the restrictions of doing so on a free vs credit-card / paid account.

**Comment by Zrrrpy** [comment]
Thanks @lauramosher! I'll add this to our list of setup needs this week and will close this out.
