### ISSUE TITLE
Email bug: Inactive volunteers list is inaccurate - tracks logged in at but login lasts several days, so do most recent of case contact created OR logged in at

### ISSUE THREAD

**Issue by dpaola2** [rubyforgood/casa#4672]
Volunteers that have been active are still showing up

**Comment by Jaskaran2** [comment]
Hi @dpaola2 is it ok if I may take a look at this issue?

**Comment by compwron** [comment]
the stakeholders asked about this again today, we are excited to fix this :)

**Comment by Jaskaran2** [comment]
Sure I am on it. Sorry for the late reply

**Comment by Jaskaran2** [comment]
Hi @dpaola2 could you help me out by providing the steps to reproduce the issue because it seems to me as if the feature is working as expected. Maybe I am not able understanding the issue clearly over here. I am attaching the video for the are I was exploring.

I deactivated 2 of the users and they were showing up in the list as expected.

https://user-images.githubusercontent.com/60808292/227794224-b6393676-40d6-4cbd-8111-868eadd74622.mov

**Comment by dpaola2** [comment]
@compwron how have you typically reconciled user-reported issues like this with an inability to reproduce?

**Comment by Jaskaran2** [comment]
Hi @dpaola2 any update on how to reproduce the issue.

**Comment by compwron** [comment]
this is because you can log in on day 1, make a case contact on day 2, and on day 2 + 30 days, the supervisor email says you haven't logged in for 30 days and is accurate but not useful- use last case contact created if it's more recent than last login
