### ISSUE TITLE
Case Contact Form Update: Change Section "1. Select the relevant cases" picker to Dropdown style like in Section 2. Select All Contact Types

### ISSUE THREAD

**Issue by bcastillo32** [rubyforgood/casa#5776]
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description:
In the volunteer view of the case contact form (`/case_contacts/:id/form/details`), there are typically only two or three cases under the “select a case” question. 

![Image](https://github.com/rubyforgood/casa/assets/14540596/daaeaa7b-66bb-4269-8745-4c13d89c42e8)

However, in the supervisor view, they see all cases handled by their volunteers. In the supervisor view, this question can be overwhelming to view.

![Image](https://github.com/rubyforgood/casa/assets/14540596/ce349e11-32f4-467c-818d-9215d99cede3)

Please apply the same picker style from Section 2 to section 1 in the Case Contact form. 
<img width="1674" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/850838f4-d785-49be-8daa-c54b1d5cdff0">

<img width="1667" alt="image" src="https://github.com/rubyforgood/casa/assets/77401173/104bae19-a422-40c3-9089-3a31e75a37d2">

Criteria for completion:

- [ ] update the UI to a multi-select instead of a checkbox selection 
- [ ] make sure that users are able to select multiple cases since they could be filling out a case contact for siblings
- [ ] in the supervisor view, make sure that the dropdown includes volunteer name after case to assist in selecting the correct case

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by kenny-luong** [comment]
Happy to work on this

**Comment by kenny-luong** [comment]
So I noticed an issue with one of the specs.

`spec/system/case_contacts/new_spec.rb`

`line 128: re-renders the form with errors, but preserving all previously entered selections`

My understanding of this spec is that it's not only testing error enforcing, but also making sure that it retains the previous selections.

It seems that "Contact Type" is not actually a required field despite being labeled as one. 

<img width="662" alt="image" src="https://github.com/rubyforgood/casa/assets/15682136/88138fee-4287-49ee-94f8-de1d5f3f70cf">

You can actually move forward in the form without having selected a contact type.

This is happening because we call `complete_details_page` twice. The first time will select all of the contact types as expected but the second call actually removes all of the selections.

Thoughts on what we want to do here? This is preventing me from updating the spec to handle the case selection.
