### ISSUE TITLE
add checkboxes to skip later pages of the case contact form

### ISSUE THREAD

**Issue by elasticspoon** [rubyforgood/casa#5926]
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

The main flow of our application is case contact creation (`/case_contacts/:id/form`), we want this process to be as quick and seamless for volunteers are possible. 

Volunteers have stated to us that they have to perform a lot of extra clicks when submitting a case contact but they don't have notes or driving info to enter. 

Lets add some buttons that will allow the volunteers to optionally skip past those pages in the form.

![Image](https://github.com/user-attachments/assets/71ac0e29-f6a5-4cda-aae1-04a79ea2ad46)

## Criteria for Completion

- [ ] On the first page of the form add toggles to skip notes and expenses
- [ ] On the notes page add a toggle to skip expenses
- [ ] Make sure the expenses toggle does not show if the users can't set expenses
- [ ] We have a `jsonb` field `metadata` on each case contact. Store whether a user chose to use those buttons or not in the json metadata so we can measure how useful these buttons are later.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by jamesh38** [comment]
I've taken a look at this one and have got some buttons added that are passing their status up to the controller on form submit. 

![Screenshot 2024-08-08 at 6 22 38 PM](https://github.com/user-attachments/assets/4d195538-6fb2-4e45-b5c8-5109f56e6778)

I'd be happy to take this one to the finish line if you'd like to assign it to me. Definitely have a few questions

1. Would you prefer we override the next step at the controller level or would we rather dive into the wizard and make some modifications there? Still wrapping my head around that gem and how it works
2. Would you like to add some javascript that changes the submit button component text on the client side to "Submit" whenever all relevant skips are checked?
3. Are we using any tooling to auto format ERB files because the tool I'm using is completely reformatting the `details.html.erb` file and I would feel bad committing all that if its not preferred or we have another solution

**Comment by elasticspoon** [comment]
> I'd be happy to take this one to the finish line if you'd like to assign it to me. Definitely have a few questions if so. Can transfer these to a draft PR if you'd like.

Sound good @jamesh38 

>     1. Would you prefer we override the next step at the controller level or would we rather dive into the wizard and make some modifications there? Still wrapping my head around that gem and how it works

I believe you will have to do it at a controller level (I think most of the wizard related logic lives in the controllers and some in the CaseContact model). The wizard is an external gem so we can't really modify it. 

>     2. Would you like to add some javascript that changes the submit button component text on the client side to "Submit" whenever all relevant skips are checked?

I would consider that a "nice to have" but its not required for the sake of the PR.
 
>     3. Are we using any tooling to auto format ERB files because the tool I'm using is completely reformatting the `details.html.erb` file and I would feel bad committing all that if its not preferred or we have another solution

We use erb_lint. You can lint the project running `bin/lint`. It would be preferred if you didn't commit significant formatting changes alongside behavior changes just because it makes it way harder to follow the changes in behavior.

**Comment by jamesh38** [comment]
Thanks @elasticspoon I'll be taking a look at this and finishing up this week.

**Comment by thejonroberts** [comment]
Resolved in #6048 - form is single page now.

**Comment by jamesh38** [comment]
Life happened and I didn't finish this one apologies there folks. Are we good to close this then now if it's no longer relevant? @elasticspoon @thejonroberts
