### ISSUE TITLE
Unhandled error in supervisor_volunteers#create

### ISSUE THREAD

**Issue by strangrjrjr** [rubyforgood/casa#640]
**What is the problem, and what should happen instead?**
When assigning volunteers on the Supervisor edit page, a warning appears when no active, unassigned volunteers are available, but clicking the "Assign Volunteer" button again produces an unhandled error.

**Screenshots of current behavior, if any**

**No volunteers available**
![Screen Shot 2020-09-03 at 11 14 28 AM](https://user-images.githubusercontent.com/5456014/92151873-ab3e6a00-edd6-11ea-8456-3f1d515eb70a.png)

**Click Assign Volunteer**
![Screen Shot 2020-09-03 at 11 14 09 AM](https://user-images.githubusercontent.com/5456014/92151908-b8f3ef80-edd6-11ea-994c-42632d228f59.png)

**Comment by Zrrrpy** [comment]
This looks a lot like #638 and I suspect may be related

**Comment by Zrrrpy** [comment]
@jmkoni when you merge #638, can you check to see if it resolves this?

**Comment by compwron** [comment]
This bug is still a bug 
![Screen Shot 2020-09-05 at 9 43 47 AM](https://user-images.githubusercontent.com/578159/92309663-54629d00-ef5c-11ea-89d9-919acd312023.png)
![Screen Shot 2020-09-05 at 9 43 43 AM](https://user-images.githubusercontent.com/578159/92309665-5593ca00-ef5c-11ea-8aaf-28d12b3592fd.png)
