### ISSUE TITLE
Report filters

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#662]
Part of epic #529

**What type of user is this for? [admin/volunteer/supervisor/all or All CASA Admin]**
admins and supervisors

**Where does/should this occur**
On the <a href="https://casa-r4g-staging.herokuapp.com/reports">Generate Reports page.</a>

**Description**
In addition to "starting from" and "end date" filters for reports, users should be able to filter by any combination of the following:
[ ] Assigned to supervisors (choose from multi-select dropdown)
[ ] Volunteers a.k.a `created_by` (choose from multi-select dropdown)
[ ] Contact type (choose from multi-select dropdown)
[ ] Wants driving reimbursement (two checkboxes: yes / no)
[ ] Contact made (two checkboxes: yes / no)
[ ] Transition aged youth (two checkboxes: yes/no)

**Comment by jmkoni** [comment]
#698 should be ready to review. Changed a couple of things:
- contact_type has to be single select for now. We can maybe change it to multi-select but that query is hard 😰 
- wants driving reimbursement, contact made, and has transitioned will also be selects (with the option to not select). Since they are boolean values, it made more sense to just pass one or not at all.

**Comment by jmkoni** [comment]
Frontend still needs to be done 😅
