### ISSUE TITLE
Update error message for failed case imports

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#707]
Update error message for failed case imports
If the same case is in the import file twice, the error message should be in green "One case ABC imported" and in red "Case ABC not imported because it already exists"
![92675091-7dc05780-f2d3-11ea-8c13-2d6cc9d61fda](https://user-images.githubusercontent.com/578159/92675541-7c435f00-f2d4-11ea-8af0-46e35a3f3cc9.png)
Avoid working on this until https://github.com/rubyforgood/casa/pull/624 is merged

**Comment by dominiquecuevas** [comment]
![image](https://user-images.githubusercontent.com/56096225/92675091-7dc05780-f2d3-11ea-8c13-2d6cc9d61fda.png)

**Comment by keithrbennett** [comment]
The number of duplicates could be too many to fit into a flash message without being unreadable. Maybe we need an error dialog?

Also, it might not be difficult to analyze the file for duplicates in advance of passing it to the importer. That may be a simpler approach, since we would not have to differentiate between duplicates and other errors.

**Comment by Zrrrpy** [comment]
@compwron any flags for closing this and replacing with #798?

**Comment by compwron** [comment]
@Zrrrpy sounds good to me!
