### ISSUE TITLE
Occurred at calendar not displaying in Safari on desktop and mobile web

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#820]
Part of epic #3

**What type of user is this for? [admin/volunteer/supervisor/all or All CASA Admin]**
primarily volunteer, but also admin and supervisor

**Where does/should this occur?**
On the create/edit case contact page accessible via all user dashboards.

**Desired behavior**
A small calendar icon should display on the far right of the "Occurred at" field. Clicking this calendar should trigger a calendar pop out that users can use to select a date to associate with their `case_contact`. 

**Current behavior**
No calendar icon displays in the "Occurred at" field **when accessed on Safari** (mobile and desktop web). 

The fix to this will probably to use some library which makes Safari respect https://caniuse.com/input-datetime
<img width="840" alt="Screen Shot 2020-10-11 at 10 30 11 AM" src="https://user-images.githubusercontent.com/578159/95685449-d1f97880-0bac-11eb-892a-d3ffd6f932e8.png">
I checked and it it does work on Firefox and Chrome.

**Comment by casadei** [comment]
I spent some time investigating this problem and figured out that Safari desktop [is not compatible](https://caniuse.com/input-datetime) with date type inputs. So, that's why the datepicker is not shown. 

I left this card to let someone more familiar with front-end stuff/libraries/compatibilities solve this issue.

**Comment by stevelandwehr** [comment]
Firefox has partial date input support, but the calendar icon doesn't show up in the input in Firefox.

**Comment by NickSchimek** [comment]
Since we are already using bootstrap I think I will go with this solution here: https://bootstrap-datepicker.readthedocs.io/en/latest/

It does not utilize the HTML5 date attribute. Hence, It will provide a uniform look across all browsers.
Because of that the `type=date` will be changed to `type=text` - I'm not sure if this would impact accessibility in any way. Perhaps there is an aria label that can be added if it does. If changing the type attr would be an issue then there are other options we can utilize that keeps the type attribute set to date.
